# **************************************************
# *  Author: Iceyee                                *
# *  Mail: iceyee.studio@qq.com                    *
# *  Git: https://github.com/iceyee                *
# **************************************************
#                                                   
[package]
name = "iceyee_webdriver"
version = "8.0.1"
edition = "2024"

description = "web selenium."
keywords = ["iceyee"]
license = "Apache-2.0"
repository = "https://github.com/iceyee/rust_iceyee/tree/main/iceyee_webdriver/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iceyee_logger = "13" 
iceyee_random = "13" 
iceyee_time = "13" 
serde_json = "1.0" 
thirtyfour = "0.37"
tokio = { version = "1", features = ["full"] } 
