# **************************************************
# *  Author: Iceyee                                *
# *  Mail: iceyee.studio@qq.com                    *
# *  Git: https://github.com/iceyee                *
# **************************************************
#                                                   
[package]
name = "iceyee_net"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-compression = { version = "0.4", features = ["all"] }
async-trait = "=0.1"
iceyee_encoder = "1.3"
iceyee_error = "1.0"
iceyee_random= "1.0"
native-tls = "0.2"
tokio = { version = "1", features = ["full"] }
tokio-native-tls = "0.3"
